
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JColorChooser;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Vince
 */
public class Settings extends JFrame {
    private JFrame System;
    
    /**
     * Creates new form settings
     */
    public Settings(System system) {
        initComponents();
        onRun();
        Color color = Login.bg_cl;
        Color color1 = Login.font_cl;
        bg_pnl.setBackground(color);
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_pnl = new javax.swing.JPanel();
        change_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        bg_btn = new javax.swing.JButton();
        font_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bg_pnl.setBackground(new java.awt.Color(255, 255, 255));
        bg_pnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        change_btn.setText("Change Password");
        change_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_btnActionPerformed(evt);
            }
        });

        logout_btn.setText("Log out");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });

        bg_btn.setText("Background Color");
        bg_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bg_btnMouseClicked(evt);
            }
        });

        font_btn.setText("Font Color");
        font_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                font_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg_pnlLayout = new javax.swing.GroupLayout(bg_pnl);
        bg_pnl.setLayout(bg_pnlLayout);
        bg_pnlLayout.setHorizontalGroup(
            bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_pnlLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(font_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bg_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(change_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(101, 101, 101))
        );
        bg_pnlLayout.setVerticalGroup(
            bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_pnlLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(font_btn)
                .addGap(18, 18, 18)
                .addComponent(bg_btn)
                .addGap(18, 18, 18)
                .addComponent(change_btn)
                .addGap(18, 18, 18)
                .addComponent(logout_btn)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_pnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private System system;
    
    private void change_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_btnActionPerformed
        // TODO add your handling code here:
        Change c = new Change();
        FrameColorUtil.setColors(c, Login.font_cl, Login.bg_cl);
        c.setAlwaysOnTop(true);
        c.setVisible(true);
    }//GEN-LAST:event_change_btnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        // TODO add your handling code here:
        dispose();
        system.dispose();
        Login l = new Login();
        FrameColorUtil.setColors(l, Login.font_cl, Login.bg_cl);
        l.setVisible(true);
    }//GEN-LAST:event_logout_btnActionPerformed

    private void font_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_font_btnMouseClicked
        // TODO add your handling code here:
        Login.font_cl = JColorChooser.showDialog(this, "Choose Font Color", Login.font_cl);
        dispose();
        system.dispose();
        new System().setVisible(true);
    }//GEN-LAST:event_font_btnMouseClicked

    private void bg_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_btnMouseClicked
        // TODO add your handling code here:
        Login.bg_cl = JColorChooser.showDialog(this, "Choose Background Color", Login.bg_cl);
        dispose();
        system.dispose();
        new System().setVisible(true);
    }//GEN-LAST:event_bg_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    
    private void onRun() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        setTitle("Settings");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bg_btn;
    private javax.swing.JPanel bg_pnl;
    private javax.swing.JButton change_btn;
    private javax.swing.JButton font_btn;
    private javax.swing.JButton logout_btn;
    // End of variables declaration//GEN-END:variables
}
