import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.text.PlainDocument;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Vince
 */
public class Change extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Change() {
        initComponents();
        onRun();
        Color color = Login.bg_cl;
        Color color1 = Login.font_cl;
        bg_pnl.setBackground(color);
        
        // Usage
        PlainDocument document = new PlainDocument();
        document.setDocumentFilter(createLimitFilter(30));
        pass_tf.setDocument(document);

        PlainDocument document1 = new PlainDocument();
        document1.setDocumentFilter(createLimitFilter(30));
        npass_tf.setDocument(document1);
        
        PlainDocument document2 = new PlainDocument();
        document2.setDocumentFilter(createLimitFilter(30));
        cnpass_tf.setDocument(document2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_pnl = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        cpass_btn = new javax.swing.JButton();
        npass_tf = new javax.swing.JPasswordField();
        cnpass_tf = new javax.swing.JPasswordField();
        label3 = new javax.swing.JLabel();
        cancel_btn = new javax.swing.JButton();
        pass_tf = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bg_pnl.setBackground(new java.awt.Color(255, 255, 255));
        bg_pnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bg_pnl.setPreferredSize(new java.awt.Dimension(355, 285));

        label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("CHANGE PASSWORD");

        label1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label1.setText("Password:");

        label2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label2.setText("New Password:");

        cpass_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cpass_btn.setText("Change Password");
        cpass_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpass_btnActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label3.setText("Confirm New Password:");

        cancel_btn.setText("Cancel");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_pnlLayout = new javax.swing.GroupLayout(bg_pnl);
        bg_pnl.setLayout(bg_pnlLayout);
        bg_pnlLayout.setHorizontalGroup(
            bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_pnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_pnlLayout.createSequentialGroup()
                        .addComponent(cpass_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(npass_tf)
                        .addComponent(cnpass_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pass_tf)))
                .addGap(21, 21, 21))
        );
        bg_pnlLayout.setVerticalGroup(
            bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_pnlLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(pass_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2)
                    .addComponent(npass_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label3)
                    .addComponent(cnpass_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpass_btn)
                    .addComponent(cancel_btn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public SysPrint sysPrint = new SysPrint();
    public static int ID;
    
    public DocumentFilter createLimitFilter(int limit) {
        return new DocumentFilter() {
            @Override
            public void insertString(DocumentFilter.FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
                if (fb.getDocument().getLength() + string.length() <= limit) {
                    super.insertString(fb, offset, string, attr);
                }
            }

            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                if (fb.getDocument().getLength() - length + text.length() <= limit) {
                    super.replace(fb, offset, length, text, attrs);
                } else {
                    JFrame frame = new JFrame("Maximum Character");
                    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    frame.setAlwaysOnTop(true);
                    JOptionPane.showMessageDialog(frame, "Maximum Character: " + limit, "Maximum Character", JOptionPane.WARNING_MESSAGE);
                }
            }
        };
    }
    
    private void cpass_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpass_btnActionPerformed
        // TODO add your handling code here:
        try
        {
            Driver mySqlDriver = DriverManager.getDriver("jdbc:mysql://localhost:3306/");
            Properties prop = new Properties();
            prop.put("user", "root");
            prop.put("password", "");
            Connection con = (Connection) mySqlDriver.connect("jdbc:mysql://localhost:3306/taskmngmnt", prop);
            
            
            String password = pass_tf.getText();
            String npassword = npass_tf.getText();
            String cnpassword = cnpass_tf.getText();
            
            Statement stm = con.createStatement();
            
            String sql = "select * from users where id='"+ID+"' and password='"+password+"'";
            ResultSet rs = stm.executeQuery(sql);
            
            if(!rs.next()) {
                sysPrint.sysP(0, "Wrong password!");
                JOptionPane.showMessageDialog(this, "Wrong password!");
                pass_tf.setText("");
                npass_tf.setText("");
                cnpass_tf.setText("");
                
            } else {
                String pw = rs.getString("password");
                sysPrint.sysP(1, "Password: " + pw);
                
                if (password.equals(pw)) {
                    if (npassword.isEmpty() || cnpassword.isEmpty()) {
                        sysPrint.sysP(0, "No empty fields allowed!");
                        JOptionPane.showMessageDialog(this, "No empty fields allowed!");
                    } else if (!npassword.equals(cnpassword)) {
                        sysPrint.sysP(0, "New Password and Confirm\nNew Password fields do not match!");
                        JOptionPane.showMessageDialog(this, "New Password and Confirm\nNew Password fields do not match!");
                    } else {
                        String q2 = "UPDATE users SET password = '" +npassword+ "' WHERE id = '"+ID+"'";
                        int check = stm.executeUpdate(q2);

                        if (check > 0) {
                            sysPrint.sysP(1, "Password successfully updated.");
                            JOptionPane.showMessageDialog(this, "Password successfully updated!");
                        } else {
                            sysPrint.sysP(0, "Error occurred while updating password!");
                            JOptionPane.showMessageDialog(this, "Error occurred while updating password!");
                        }
                        dispose();
                    }
                }
                else {
                    sysPrint.sysP(0, "Wrong password!");
                    JOptionPane.showMessageDialog(this, "Wrong password!");
                    pass_tf.setText("");
                    npass_tf.setText("");
                    cnpass_tf.setText("");
                }
            }
            con.close();
            
        } catch(Exception e) {
            sysPrint.sysP(0, e.getMessage());
        }
    }//GEN-LAST:event_cpass_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        sysPrint.sysP(1, "ID: " + ID);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    
    private void onRun() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        setTitle("Change Password");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_pnl;
    private javax.swing.JButton cancel_btn;
    public javax.swing.JPasswordField cnpass_tf;
    private javax.swing.JButton cpass_btn;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    public javax.swing.JPasswordField npass_tf;
    public javax.swing.JPasswordField pass_tf;
    // End of variables declaration//GEN-END:variables
}
