import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.text.PlainDocument;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Vince
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        onRun();
        bg_pnl.setBackground(bg_cl);
        
        // Usage
        PlainDocument document = new PlainDocument();
        document.setDocumentFilter(createLimitFilter(30));
        username_tf.setDocument(document);

        PlainDocument document1 = new PlainDocument();
        document1.setDocumentFilter(createLimitFilter(30));
        password_tf.setDocument(document1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_pnl = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        username_tf = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        login_btn = new javax.swing.JButton();
        register_btn = new javax.swing.JButton();
        password_tf = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        bg_pnl.setBackground(new java.awt.Color(255, 255, 255));
        bg_pnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bg_pnl.setPreferredSize(new java.awt.Dimension(355, 285));

        label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("LOGIN");

        label1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label1.setText("Username:");

        label2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label2.setText("Password:");

        login_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        login_btn.setText("Login");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });

        register_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        register_btn.setText("Register");
        register_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_pnlLayout = new javax.swing.GroupLayout(bg_pnl);
        bg_pnl.setLayout(bg_pnlLayout);
        bg_pnlLayout.setHorizontalGroup(
            bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bg_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bg_pnlLayout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(username_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bg_pnlLayout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(password_tf)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_pnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(register_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132))
        );
        bg_pnlLayout.setVerticalGroup(
            bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_pnlLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(username_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2)
                    .addComponent(password_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(login_btn)
                .addGap(18, 18, 18)
                .addComponent(register_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public SysPrint sysPrint = new SysPrint();
    public static Color bg_cl = Color.white;
    public static Color font_cl = Color.black;
    
    public DocumentFilter createLimitFilter(int limit) {
        return new DocumentFilter() {
            @Override
            public void insertString(DocumentFilter.FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
                if (fb.getDocument().getLength() + string.length() <= limit) {
                    super.insertString(fb, offset, string, attr);
                }
            }

            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                if (fb.getDocument().getLength() - length + text.length() <= limit) {
                    super.replace(fb, offset, length, text, attrs);
                } else {
                    JFrame frame = new JFrame("Maximum Character");
                    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    frame.setAlwaysOnTop(true);
                    JOptionPane.showMessageDialog(frame, "Maximum Character: " + limit, "Maximum Character", JOptionPane.WARNING_MESSAGE);
                }
            }
        };
    }
    
    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        // TODO add your handling code here:
        try
        {
            Driver mySqlDriver = DriverManager.getDriver("jdbc:mysql://localhost:3306/");
            Properties prop = new Properties();
            prop.put("user", "root");
            prop.put("password", "");
            Connection con = (Connection) mySqlDriver.connect("jdbc:mysql://localhost:3306/taskmngmnt", prop);
            
            
            String username = username_tf.getText();
            String password = password_tf.getText();

            Statement stm = con.createStatement();
            
            String sql = "select * from users where username='"+username+"' and password='"+password+"'";
            ResultSet rs = stm.executeQuery(sql);
            
            if(rs.next()) {
                int id = rs.getInt("id");
                sysPrint.sysP(1, "User ID: " + id);
                String un = rs.getString("username");
                String pw = rs.getString("password");
                
                sysPrint.sysP(1, "Username: " + un);
                sysPrint.sysP(1, "Password: " + pw);
                
                if (username.equals(un) && password.equals(pw)) {
                    System sys = new System();
                    sys.setVisible(true);
                    sys.ID = id;
                    dispose();
                }
                else {
                    sysPrint.sysP(0, "Username, or Password is wrong!");
                    JOptionPane.showMessageDialog(this, "Username, or Password is wrong!");
                    username_tf.setText("");
                    password_tf.setText("");
                }
                
            } else {
                sysPrint.sysP(0, "Username, or Password is wrong!");
                JOptionPane.showMessageDialog(this, "Username, or Password is wrong!");
                username_tf.setText("");
                password_tf.setText("");
            }
            con.close();
            
        } catch(Exception e) {
            sysPrint.sysP(0, e.getMessage());
        }
    }//GEN-LAST:event_login_btnActionPerformed

    private void register_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_btnActionPerformed
        // TODO add your handling code here:
        dispose();
        Register r = new Register();
        FrameColorUtil.setColors(r, Login.font_cl, Login.bg_cl);
        r.setVisible(true);
    }//GEN-LAST:event_register_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login main = new Login();
                main.setVisible(true);
            }
        });
    }
    
    private void onRun() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        setTitle("Authentication: Login");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_pnl;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JButton login_btn;
    public javax.swing.JPasswordField password_tf;
    private javax.swing.JButton register_btn;
    public javax.swing.JTextField username_tf;
    // End of variables declaration//GEN-END:variables
}
