import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.text.PlainDocument;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Vince
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Register() {
        initComponents();
        onRun();
        Color color = Login.bg_cl;
        Color color1 = Login.font_cl;
        bg_pnl.setBackground(color);
        // Usage
        PlainDocument document = new PlainDocument();
        document.setDocumentFilter(createLimitFilter(30));
        username_tf.setDocument(document);

        PlainDocument document1 = new PlainDocument();
        document1.setDocumentFilter(createLimitFilter(30));
        password_tf.setDocument(document1);
        
        PlainDocument document2 = new PlainDocument();
        document2.setDocumentFilter(createLimitFilter(30));
        conpass_tf.setDocument(document2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_pnl = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        username_tf = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        register_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        password_tf = new javax.swing.JPasswordField();
        conpass_tf = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg_pnl.setBackground(new java.awt.Color(255, 255, 255));
        bg_pnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bg_pnl.setPreferredSize(new java.awt.Dimension(355, 285));

        label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("REGISTER");

        label1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label1.setText("Username:");

        label2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label2.setText("Password:");

        label3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label3.setText("Confirm Password:");

        register_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        register_btn.setText("Register");
        register_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_btnActionPerformed(evt);
            }
        });

        back_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_pnlLayout = new javax.swing.GroupLayout(bg_pnl);
        bg_pnl.setLayout(bg_pnlLayout);
        bg_pnlLayout.setHorizontalGroup(
            bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_pnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(register_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addGroup(bg_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bg_pnlLayout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(username_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_pnlLayout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(password_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bg_pnlLayout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(conpass_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        bg_pnlLayout.setVerticalGroup(
            bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(username_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2)
                    .addComponent(password_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label3)
                    .addComponent(conpass_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(register_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public SysPrint sysPrint = new SysPrint();
    
    public DocumentFilter createLimitFilter(int limit) {
        return new DocumentFilter() {
            @Override
            public void insertString(DocumentFilter.FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
                if (fb.getDocument().getLength() + string.length() <= limit) {
                    super.insertString(fb, offset, string, attr);
                }
            }

            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                if (fb.getDocument().getLength() - length + text.length() <= limit) {
                    super.replace(fb, offset, length, text, attrs);
                } else {
                    JFrame frame = new JFrame("Maximum Character");
                    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    frame.setAlwaysOnTop(true);
                    JOptionPane.showMessageDialog(frame, "Maximum Character: " + limit, "Maximum Character", JOptionPane.WARNING_MESSAGE);
                }
            }
        };
    }
    
    private void register_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_btnActionPerformed
        // TODO add your handling code here:
        java.lang.System.out.println(username_tf.getText());
        if (password_tf.getText().equals(conpass_tf.getText()) && !password_tf.getText().isEmpty()) {
            if (!username_tf.getText().isEmpty()) {
                try {
                    Driver mySqlDriver = DriverManager.getDriver("jdbc:mysql://localhost:3306/");
                    Properties prop = new Properties();
                    prop.put("user", "root");
                    prop.put("password", "");
                    Connection con = (Connection) mySqlDriver.connect("jdbc:mysql://localhost:3306/taskmngmnt", prop);


                    String username = username_tf.getText();
                    String password = password_tf.getText();

                    Statement stm = con.createStatement();

                    String sqlInsert = "INSERT INTO users (username, password) VALUES (?, ?)";
                    PreparedStatement ps = (PreparedStatement) con.prepareStatement(sqlInsert);

                    ps.setString(1, username_tf.getText());
                    ps.setString(2, password_tf.getText());

                    String sql = "select * from users where username='"+username+"'";
                    ResultSet rs = stm.executeQuery(sql);

                    if(rs.next()) {
                        java.lang.System.out.println("Username is null, or already taken!");
                        JOptionPane.showMessageDialog(this, "Username  is null, or already taken!");
                    } else {
                        ps.execute();

                        java.lang.System.out.println("Registered Successfully!");
                        JOptionPane.showMessageDialog(this, "Registered Successfully!");
                        dispose();
                        Login l = new Login();
                        FrameColorUtil.setColors(l, Login.font_cl, Login.bg_cl);
                        l.setVisible(true);
                    }
                } catch(Exception e) {
                    sysPrint.sysP(0, e.getMessage());
                }
            } else {
                sysPrint.sysP(1, "Fields are empty!");
            }
        }
        else {
            sysPrint.sysP(0, "Passwords are not the same, or empty!");
            JOptionPane.showMessageDialog(this, "Passwords are not the same, or empty!");
            password_tf.setText("");
            conpass_tf.setText("");
        }
    }//GEN-LAST:event_register_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        dispose();
        Login l = new Login();
        FrameColorUtil.setColors(l, Login.font_cl, Login.bg_cl);
        l.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    
    private void onRun() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        setTitle("Authentication: Register");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JPanel bg_pnl;
    private javax.swing.JPasswordField conpass_tf;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JPasswordField password_tf;
    private javax.swing.JButton register_btn;
    private javax.swing.JTextField username_tf;
    // End of variables declaration//GEN-END:variables
}
