import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.Properties;
import javax.swing.table.DefaultTableModel;
import java.util.Arrays;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Vince
 */
public class System extends javax.swing.JFrame {

    /**
     * Creates new form System
     */
    public System() {
        initComponents();
        onRun();
        bg_pnl.setBackground(color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_pnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        task_table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        add_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        refresh_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        desc_f = new javax.swing.JTextArea();
        settings_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        search_tf = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bg_pnl.setBackground(new java.awt.Color(255, 255, 255));
        bg_pnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        task_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        task_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task Number", "Task Name", "Due Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        task_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                task_tableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(task_table);

        add_btn.setText("Add");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        refresh_btn.setText("Refresh");
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refresh_btn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(refresh_btn)
                .addGap(18, 18, 18)
                .addComponent(add_btn)
                .addGap(18, 18, 18)
                .addComponent(update_btn)
                .addGap(18, 18, 18)
                .addComponent(delete_btn)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jLabel1.setFont(jLabel1.getFont());
        jLabel1.setText("Task Description");

        desc_f.setEditable(false);
        desc_f.setColumns(20);
        desc_f.setRows(5);
        jScrollPane2.setViewportView(desc_f);

        settings_btn.setText("Settings");
        settings_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settings_btnActionPerformed(evt);
            }
        });

        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search_tf)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(search_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(43, 43, 43)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(100, Short.MAX_VALUE)
                    .addComponent(search_btn)
                    .addContainerGap(72, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout bg_pnlLayout = new javax.swing.GroupLayout(bg_pnl);
        bg_pnl.setLayout(bg_pnlLayout);
        bg_pnlLayout.setHorizontalGroup(
            bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_pnlLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_pnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(settings_btn)))
                .addContainerGap())
        );
        bg_pnlLayout.setVerticalGroup(
            bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_pnlLayout.createSequentialGroup()
                .addGroup(bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bg_pnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(bg_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bg_pnlLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116))
                            .addGroup(bg_pnlLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(settings_btn)
                                .addGap(8, 8, 8))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public static int ID;
    public SysPrint sysPrint = new SysPrint();
    public static int task_count = 0;
    private static String[] desc = new String[100];
    private static int row;
    private static String value;
    Color color = Login.bg_cl;
    Color color1 = Login.font_cl;
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        sysPrint.sysP(1, "WINDOW OPENED!");
        count();
        refreshTable();
    }//GEN-LAST:event_formWindowOpened

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
        count();
        sysPrint.sysP(1, "" + task_count);
        addBtn.ID = ID;
        addBtn add = new addBtn(this);
        FrameColorUtil.setColors(add, Login.font_cl, Login.bg_cl);
        add.setAlwaysOnTop(true);
        add.setVisible(true);
    }//GEN-LAST:event_add_btnActionPerformed

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
        // TODO add your handling code here:
        count();
        refreshTable();
    }//GEN-LAST:event_refresh_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        updateBtn.ID = ID;
        
        int index = task_table.getSelectedRow();
        if(index != -1){
            String taskNum = task_table.getValueAt(index, 0).toString();
            String taskName = task_table.getValueAt(index, 1).toString();
            String taskDesc = desc[index];
            String due = task_table.getValueAt(index, 2).toString();
            String status = task_table.getValueAt(index, 3).toString();
            
            updateBtn.taskNum = Integer.parseInt(taskNum);
            updateBtn.taskName = taskName;
            updateBtn.taskDesc = taskDesc;
            updateBtn.due = due;
            updateBtn.status = status;
            
            updateBtn update = new updateBtn(this);
            FrameColorUtil.setColors(update, Login.font_cl, Login.bg_cl);
            update.setAlwaysOnTop(true);
            update.setVisible(true);
        }
    }//GEN-LAST:event_update_btnActionPerformed

    private void settings_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settings_btnActionPerformed
        // TODO add your handling code here:
        Settings st = new Settings(this);
        st.setVisible(true);
        Change.ID = ID;
    }//GEN-LAST:event_settings_btnActionPerformed

    private void task_tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_task_tableMouseReleased
        // TODO add your handling code here:
        row = task_table.rowAtPoint(evt.getPoint());
        value = desc[row];
        desc_f.setText(value);
        desc_f.setCaretPosition(0);
    }//GEN-LAST:event_task_tableMouseReleased

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        int index = task_table.getSelectedRow();
        int task_num = 0;
        if(index != -1){
            int dialogResult = JOptionPane.showConfirmDialog(null, "Delete this task?");
            if(dialogResult == JOptionPane.YES_OPTION){
                task_num = (int)task_table.getValueAt(index, 0);
                try {
                    Driver mySqlDriver = (Driver) DriverManager.getDriver("jdbc:mysql://localhost:3306/taskmngmnt");
                    Properties prop = new Properties();
                    prop.put("user", "root");
                    prop.put("password", "");
                    Connection con = (Connection) mySqlDriver.connect("jdbc:mysql://localhost:3306/taskmngmnt", prop);
                    sysPrint.sysP(1, "Connected to database!");

                    //DELETE statement
                    String deleteQuery = "DELETE FROM tasks WHERE task_num = ?";
                    PreparedStatement ps = (PreparedStatement) con.prepareStatement(deleteQuery);

                    ps.setInt(1, task_num);
                    ps.execute();

                    sysPrint.sysP(1, "Deleted!");

                    refreshTable();
                } catch (SQLException e) {
                    sysPrint.sysP(0, e.getMessage());
                }
            }
        }
        count();
    }//GEN-LAST:event_delete_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_search_btnActionPerformed
    
    public void refreshTable(){
        Arrays.fill(desc, "");

        String url = "jdbc:mysql://localhost:3306/taskmngmnt";
        Properties prop = new Properties();
        prop.put("user", "root");
        prop.put("password", "");

        String searchQuery = "SELECT * FROM tasks WHERE user_id LIKE ? AND (task_num LIKE ? OR task_name LIKE ? OR task_description LIKE ? OR due_date LIKE ? OR status LIKE ?)";
        try (Connection con = DriverManager.getConnection(url, prop);
        PreparedStatement ps = con.prepareStatement(searchQuery)) {
            count();

            ps.setInt(1, ID);
            ps.setInt(2, task_count);
            String searchText = "%" + search_tf.getText() + "%";
            ps.setString(3, searchText);
            ps.setString(4, searchText);
            ps.setString(5, searchText);
            ps.setString(6, searchText);

            try (ResultSet rs = ps.executeQuery()) {
                DefaultTableModel dtm = (DefaultTableModel) task_table.getModel();
                dtm.setRowCount(0);

                int strCount = 0;
                while(rs.next()){
                    String taskName = rs.getString("task_name");
                    String ddate = rs.getString("due_date");
                    if(taskName.contains(search_tf.getText()) || ddate.contains(search_tf.getText())) {
                        Object[] row = new Object[5];
                        row[0] = rs.getInt("task_num");
                        row[1] = taskName;
                        desc[strCount] = rs.getString("task_description");
                        row[2] = rs.getString("due_date");
                        row[3] = rs.getString("status");
                        dtm.addRow(row);
                        strCount++;
                    }
                }
                int previous_row = row;
                value = desc[previous_row];
                desc_f.setText(value);
                desc_f.setCaretPosition(0);
            }
            sysPrint.sysP(1, "Table Retrieved!");
        } catch (SQLException e) {
            sysPrint.sysP(0, e.getMessage());
        }
    }
    
    public static void count() {
        String url = "jdbc:mysql://localhost:3306/taskmngmnt";
        Properties prop = new Properties();
        prop.put("user", "root");
        prop.put("password", "");
        int userId = ID;

        String countQuery = "SELECT COUNT(*) AS task_count FROM tasks WHERE user_id = ?";
        try (Connection con = DriverManager.getConnection(url, prop);
             PreparedStatement ps = con.prepareStatement(countQuery)) {
            
            Statement stmt = con.createStatement();

            stmt.execute("SET @num := 0;");
            stmt.execute("UPDATE tasks SET task_num = @num := (@num+1) WHERE user_id = " + ID);
            stmt.execute("ALTER TABLE tasks AUTO_INCREMENT = 0;");
            
            
            ps.setInt(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    int taskCount = rs.getInt("task_count");
                    task_count = taskCount;
                    addBtn.tCount = task_count;
                }
            }
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    
    private void onRun() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        setTitle("Task Management System");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JPanel bg_pnl;
    private javax.swing.JButton delete_btn;
    private javax.swing.JTextArea desc_f;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refresh_btn;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField search_tf;
    private javax.swing.JButton settings_btn;
    public javax.swing.JTable task_table;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
